export const tableData = [
  { name: "משה", stat: "אולי", amount: 0, message: "" },
  { name: "איציק", stat: "אולי", amount: 0, message: "" },
  { name: "רמי", stat: "אין מענה", amount: 0, message: "" },
  { name: "דני", stat: "אולי", amount: 0, message: "יולדת" },
  { name: "יפה", stat: "אושר", amount: 4, message: "" },
  { name: "דודי", stat: "אושר", amount: 1, message: "בייביסיטר" },
  { name: "עידו לוי", stat: "סורב", amount: 0, message: "" },
  { name: "דפנה", stat: "סורב", amount: 0, message: "" },
  { name: "קרן", stat: "אולי", amount: 0, message: "" },
  { name: "שימי", stat: "אושר", amount: 1, message: "אולי טס לחול" },
  { name: "אלון", stat: "אין מענה", amount: 0, message: "" },
  { name: "אופק", stat: "אושר", amount: 5, message: "" },
  { name: "גון", stat: "אולי", amount: 0, message: "" },
  { name: "ענת", stat: "אושר", amount: 4, message: "אולי טס לחול" },
  { name: "רוסיה רנדומלית", stat: "אושר", amount: 0, message: "בלאט" },
  { name: "קטי", stat: "אולי", amount: 0, message: "" },
  { name: "עמוס", stat: "סורב", amount: 0, message: "" },
  { name: "סהר", stat: "סורב", amount: 0, message: "" },
  { name: "עידן", stat: "אושר", amount: 2, message: "" },
  { name: "דודי", stat: "אין מענה", amount: 0, message: "" },
];
